version: "3.8"

services:
  drcdraw:
    image: nielmerzaaa/drcdraw:latest
    container_name: drcdraw
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=drcdraw.local
    ports:
      - "8080:80"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy_default
